version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cldr:
        patterns:
          - "cldr-*"
    commit-message:
      prefix: "chore"
      include: "scope"