name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    NODE_VERSION: '20'

jobs:
    typecheck:
        runs-on: ubuntu-latest
        name: Type Check

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Type check
              run: npm run typecheck

    formatting:
        runs-on: ubuntu-latest
        name: Check Formatting

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Check formatting
              run: npm run format:check

    build:
        runs-on: ubuntu-latest
        name: Build

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build
