name: Update Timezone Data

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - 'package-lock.json'

jobs:
    update-data:
        runs-on: ubuntu-latest
        name: Update Timezone Data

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Generate timezone data
              run: npm run generate

            - name: Format generated files
              run: npm run format

            - name: Extract CLDR version
              id: cldr_version
              run: |
                  CLDR_VERSION=$(grep "CLDR version:" src/timezone-data.ts | sed 's/.*CLDR version: //')
                  echo "version=$CLDR_VERSION" >> $GITHUB_OUTPUT

            - name: Check for changes
              id: changes
              run: |
                  if git diff --quiet; then
                    echo "has_changes=false" >> $GITHUB_OUTPUT
                  else
                    echo "has_changes=true" >> $GITHUB_OUTPUT
                  fi

            - name: Create changeset
              if: steps.changes.outputs.has_changes == 'true'
              run: |
                  cat > .changeset/update-cldr-${{ steps.cldr_version.outputs.version }}.md << EOF
                  ---
                  "winzones": minor
                  ---

                  Update timezone data to CLDR ${{ steps.cldr_version.outputs.version }}
                  EOF

            - name: Commit and push changes
              if: steps.changes.outputs.has_changes == 'true'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add .
                  git commit -m "chore: update timezone data to CLDR ${{ steps.cldr_version.outputs.version }}"
                  git push
